{% set name = "quarticRootsFlocke" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ebertolazzi/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 70ce787059845d1ae4515eab142267fb412b00613e3e17853a1b40afe781f90e
  patches:
    - patches/0014-Print-all-install-messages.patch
    - patches/0015-Generate-Config-files.patch
    - patches/0016-Use-standard-generated-library-filename.patch
    - patches/0017-Fix-package-version-when-not-in-a-git-repo.patch
    - patches/0018-Fix-QUARTIC_INCLUDE_DIRS-to-not-include-lib.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  commands:
    - bash "${RECIPE_DIR}/test.sh"  # [not win]
    - call "%RECIPE_DIR%/test.bat"  # [win]

about:
  home: https://github.com/ebertolazzi/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file: License.txt
  summary: C++ rewrite of rpoly.f
  description: |
    Port to C++ of the algorithm of Norbert Flocke for polynomial roots up to
    degree 4. Also Jenkins-Traub real polynomial root finder is ported but is
    experimental for the moment.
  doc_url: http://ebertolazzi.github.io/{{ name }}
  dev_url: https://github.com/ebertolazzi/{{ name }}

extra:
  recipe-maintainers:
    - jptiz
